package:
  name: vim
  version: "8.1"

source:
  git_rev: master
  git_url: https://github.com/vim/vim.git

requirements:
  build:
    - gcc
    - git
    - cmake
    - make
    - python==3.6.1
  run:
    - python==3.6.1

about:
  home: https://github.com/vim/vim
